-- ============================================================================
-- Seed 001 — Outfit catalog expansion (4 → 33 outfits)
--
-- Safe to run repeatedly: fixed UUIDs + ON CONFLICT DO NOTHING.
-- Replaces the 4 legacy seeds from schema.legacy.sql (their palettes used
-- names like 'Sage Green'/'Cobalt Blue' that don't exist in ColorPalette.ts,
-- which silently broke undertone scoring and the neutrals-only filter).
--
-- Editorial rules enforced in this data (do not break them when adding rows):
--  * color_palette uses EXACT swatch names from constants/ColorPalette.ts.
--  * occasions use EXACT strings from the app's occasion list, and each
--    outfit's formality is allowed by occasionToFormality for EVERY tagged
--    occasion — otherwise the hard filter guarantees the row never surfaces.
--  * Cultural rules: no Black on 'Pooja / Temple Visit'. That is the ONLY
--    colour veto — Indian weddings are maximalist and guests dress as richly
--    as they like (the "guests can't wear red/white" idea is Western wedding
--    etiquette and is deliberately NOT applied here).
--  * Every image URL was resolution-checked AND visually reviewed; the
--    description describes what is actually in the photo.
-- ============================================================================

-- Remove the 4 legacy catalog rows (known fixed IDs from schema.legacy.sql)
DELETE FROM outfit_catalog WHERE id IN (
  'a0a1a2a3-b4b5-c6c7-d8d9-e0e1e2e3e4f5',
  'b0b1b2b3-c4c5-d6d7-d8d9-e0e1e2e3e4f5',
  'c0c1c2c3-d4d5-d6d7-d8d9-e0e1e2e3e4f5',
  'd0d1d2d3-e4e5-d6d7-d8d9-e0e1e2e3e4f5'
);

INSERT INTO outfit_catalog
(id, title, image_url, occasions, style, body_types, skin_tones, formality, coverage, season, color_palette, description, explanation)
VALUES

-- ============================ ETHNIC & FESTIVE ==============================

('c1000000-0000-4000-a000-000000000001',
 'Aubergine Silk Saree with Antique Gold Zari',
 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
 ARRAY['Wedding (Close Family)', 'Reception', 'Award Ceremony / Convocation'],
 'Ethnic',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Formal', 'Conservative', 'All-season',
 ARRAY['Aubergine', 'Plum', 'Gold (Metallic)'],
 'Deep aubergine silk saree with a broad antique gold zari border, paired with a black velvet blouse and pearl drop earrings.',
 'A jewel-toned silk saree is the most reliable formal choice in Indian wardrobes — the vertical pleat line lengthens every frame, and the drape skims rather than clings, which is why it suits all body shapes. Aubergine with gold sits beautifully on every Indian skin tone and reads richer than black at a formal function.'),

('c1000000-0000-4000-a000-000000000002',
 'Rani Pink & Flame Orange Bandhani Silk Saree',
 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&auto=format&fit=crop&q=80',
 ARRAY['Sangeet Night', 'Wedding (Guest)', 'Navratri / Garba', 'Regional Festival', 'Pooja / Temple Visit', 'Baby Shower / Godh Bharai'],
 'Ethnic',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Festive', 'Conservative', 'All-season',
 ARRAY['Hot Pink', 'Orange', 'Gold'],
 'Rani pink bandhani-dot silk saree with a flame orange pallu and gold zari border, styled with a magenta puff-sleeve blouse, maang tikka and a gold choker set.',
 'Rani pink with flame orange is the great Rajasthani colour chord — pure celebration at full volume, exactly what an Indian wedding function asks for. Bandhani dots and warm gold glow on wheatish to deep skin, and the saree''s drape flatters every silhouette.'),

('c1000000-0000-4000-a000-000000000003',
 'Ivory & Gold Chikankari Anarkali Set',
 'https://images.unsplash.com/photo-1571908599407-cdb918ed83bf?w=600&auto=format&fit=crop&q=80',
 ARRAY['Wedding (Close Family)', 'Wedding (Guest)', 'Eid', 'Engagement Ceremony', 'Diwali Party (Family)'],
 'Ethnic',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Festive', 'Conservative', 'All-season',
 ARRAY['Ivory', 'Gold', 'Cream'],
 'Floor-length ivory anarkali with all-over gold threadwork in the chikankari tradition, finished with a matching net dupatta with a scalloped gold edge.',
 'Ivory-and-gold is the quiet-luxury answer to festive dressing — it photographs beautifully beside the brighter wedding palette while holding its own. The anarkali''s fitted bodice and full flare define the waist and skim the midsection, which is why it is the kindest ethnic silhouette for apple and pear shapes.'),

('c1000000-0000-4000-a000-000000000004',
 'Pearl White Net Anarkali-Sharara Set',
 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
 ARRAY['Engagement Ceremony', 'Roka / Sagai', 'Eid', 'Pooja / Temple Visit', 'Graduation Day', 'College Farewell'],
 'Ethnic',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Semi-formal', 'Conservative', 'Summer',
 ARRAY['White', 'Silver', 'Ice Blue'],
 'Pearl white net anarkali over flared sharara bottoms with fine sequin sprinkle and a trailing dupatta — light, airy and photogenic in daylight.',
 'All-white with silver shimmer is a daytime-function classic: it looks ceremonial without any heaviness, ideal for a roka, farewell or Eid lunch. Net over sharara moves with the body and flatters every shape; the cool white glows against dusky and deep skin in particular.'),

('c1000000-0000-4000-a000-000000000005',
 'Teal Georgette Flow Maxi',
 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=600&auto=format&fit=crop&q=80',
 ARRAY['Mehendi Function', 'Diwali Party (Friends)', 'Diwali Party (Family)', 'Baby Shower / Godh Bharai'],
 'Fusion',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Festive', 'Conservative', 'All-season',
 ARRAY['Teal', 'Emerald'],
 'Teal green georgette maxi with sheer full sleeves, a wrap-style bodice and a tiered flowing skirt that catches the breeze.',
 'Green is the mehendi colour family, and georgette survives hours of sitting cross-legged with hennaed hands better than any structured outfit — practical styling is good styling. The wrap bodice and tiered flare are universally forgiving, and teal is one of the few brights that flatters every undertone.'),

-- ======================= EVENING, PARTY & CELEBRATION =======================

('c1000000-0000-4000-a000-000000000006',
 'Scarlet Flare Evening Gown',
 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&auto=format&fit=crop&q=80',
 ARRAY['My Birthday', 'Reception', 'Friend''s Birthday'],
 'Western',
 ARRAY['Hourglass', 'Pear', 'Rectangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Party', 'Moderate', 'All-season',
 ARRAY['Red', 'Scarlet'],
 'Floor-sweeping scarlet gown with a fitted sleeveless bodice and a dramatic circle skirt made for twirling.',
 'Red is the most democratic celebration colour in the palette — it carries every Indian skin tone. The fitted-bodice-full-skirt cut builds an hourglass on rectangles and balances pear shapes, and the circle skirt was made for a dance floor.'),

('c1000000-0000-4000-a000-000000000007',
 'Plum Off-Shoulder Evening Gown',
 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&auto=format&fit=crop&q=80',
 ARRAY['Anniversary Dinner', 'Cocktail / Pre-wedding'],
 'Western',
 ARRAY['Hourglass', 'Pear', 'Rectangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Semi-formal', 'Minimal', 'All-season',
 ARRAY['Plum', 'Wine', 'Magenta'],
 'Body-skimming plum off-shoulder gown in a fine ribbed knit, worn with chandelier earrings and a sleek up-do.',
 'Plum is red''s more sophisticated cousin — celebratory but grown-up, perfect for an anniversary table or a cocktail evening. The off-shoulder line showcases the collarbones and visually broadens the shoulder, which balances a pear frame beautifully.'),

('c1000000-0000-4000-a000-000000000008',
 'Indigo Crochet Cut-Out Maxi',
 'https://images.unsplash.com/photo-1551803091-e20673f15770?w=600&auto=format&fit=crop&q=80',
 ARRAY['Cocktail / Pre-wedding', 'Night Out', 'My Birthday'],
 'Western',
 ARRAY['Hourglass', 'Rectangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Party', 'Minimal', 'Summer',
 ARRAY['Indigo', 'Navy', 'Cobalt'],
 'Deep indigo crochet-lace maxi with sheer sleeves and waist cut-outs, worn over a matching slip.',
 'Inky blues do everything black does at night but with more life against skin. The waist cut-outs draw a hard line at the narrowest point — a gift for rectangles wanting definition — while the crochet texture keeps it interesting up close.'),

('c1000000-0000-4000-a000-000000000009',
 'Crimson High-Neck Drape Mini',
 'https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600&auto=format&fit=crop&q=80',
 ARRAY['Night Out', 'Friend''s Birthday', 'House Party'],
 'Western',
 ARRAY['Hourglass', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Party', 'Minimal', 'All-season',
 ARRAY['Red', 'Crimson'],
 'Crimson high-neck long-sleeve mini with a sculptural floor-trailing side drape — covered on top, dramatic below.',
 'The high neck and long sleeves let the hemline and the drape do all the talking — the covered-top/short-hem trade is the most reliable formula for wearing a mini with polish. Great on inverted triangles because the eye travels down to the legs.'),

('c1000000-0000-4000-a000-000000000010',
 'Monochrome Stripe Palazzo Night Look',
 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80',
 ARRAY['Night Out', 'House Party', 'College Fest (Night)'],
 'Fusion',
 ARRAY['Hourglass', 'Pear', 'Rectangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Party', 'Moderate', 'Summer',
 ARRAY['Black', 'White', 'Red'],
 'Bold black-and-white striped wide-leg palazzos with a fitted white tank and a pop of red in a mini sling bag.',
 'Vertical stripes on a high-waisted wide leg lengthen the leg line dramatically — petite frames gain visible height. Palazzos skim the hip, which is why this silhouette is a pear shape''s best friend at a party where a bodycon feels like work.'),

('c1000000-0000-4000-a000-000000000011',
 'Black Semi-Sheer Evening Top',
 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80',
 ARRAY['Dinner Date', 'Night Out', 'House Party'],
 'Western',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Smart Casual', 'Minimal', 'All-season',
 ARRAY['Black'],
 'Relaxed black semi-sheer chiffon top with soft volume in the sleeve — pair with high-waisted trousers or a leather skirt.',
 'A sheer black top is the lowest-effort evening upgrade there is: the transparency does the styling. Because the volume is soft and unstructured it works across body shapes — the pairing below decides the mood, from dinner-date polished to house-party easy.'),

-- ========================= WORKWEAR & FORMAL ================================

('c1000000-0000-4000-a000-000000000012',
 'Ivory Power Suit with Rose Detail',
 'https://images.unsplash.com/photo-1571513722275-4b41940f54b8?w=600&auto=format&fit=crop&q=80',
 ARRAY['Job Interview (Corporate)', 'Office (Formal)', 'Client Meeting', 'Award Ceremony / Convocation'],
 'Western',
 ARRAY['Hourglass', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Formal', 'Moderate', 'All-season',
 ARRAY['Ivory', 'Cream', 'White'],
 'Tailored ivory pantsuit with a satin lapel, worn with a single deep-red rose brooch and slicked-back hair.',
 'An ivory suit commands a room more quietly than black — it signals confidence because it can''t hide stains or nerves. Structured shoulders and a straight lapel line sharpen apple and rectangle frames, and the all-neutral palette suits even the most colour-shy dresser.'),

('c1000000-0000-4000-a000-000000000013',
 'Charcoal Check Midi & Black Turtleneck',
 'https://images.unsplash.com/photo-1550639525-c97d455acf70?w=600&auto=format&fit=crop&q=80',
 ARRAY['Job Interview (Corporate)', 'Office (Formal)', 'Client Meeting', 'Internship (Corporate)', 'Award Ceremony / Convocation'],
 'Minimal',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Semi-formal', 'Conservative', 'Winter',
 ARRAY['Black', 'Charcoal', 'Grey'],
 'Fitted black turtleneck tucked into a charcoal windowpane-check wrap midi skirt with a self-tie belt, finished with a sculptural silver necklace.',
 'The turtleneck-and-midi formula is winter interview armour: covered, considered, and completely distraction-free so your answers do the talking. The wrap skirt''s tie sits at the natural waist, giving definition to every shape without a single tight seam.'),

('c1000000-0000-4000-a000-000000000014',
 'Olive Knit Midi with Camel Overcoat',
 'https://images.unsplash.com/photo-1618244972963-dbee1a7edc95?w=600&auto=format&fit=crop&q=80',
 ARRAY['Client Meeting', 'Office (Formal)', 'Anniversary Dinner'],
 'Western',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Semi-formal', 'Conservative', 'Winter',
 ARRAY['Olive', 'Camel', 'Beige'],
 'Olive ribbed-knit mock-neck midi dress under a camel wool overcoat draped on the shoulders, with block-heel sandals.',
 'Olive and camel is the warmest neutral pairing in the book — expensive-looking without a single loud note, and made for warm undertones. The column of one colour under a long coat is the oldest trick for looking taller and leaner in winter layers.'),

('c1000000-0000-4000-a000-000000000015',
 'Startup Monochrome Capsule',
 'https://images.unsplash.com/photo-1544441893-675973e31985?w=600&auto=format&fit=crop&q=80',
 ARRAY['Office (Startup)', 'Internship (Startup)', 'Job Interview (Tech)', 'WFH / Video Call'],
 'Minimal',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Smart Casual', 'Moderate', 'All-season',
 ARRAY['Grey', 'Black', 'White'],
 'The tech-office uniform done right: grey tapered trousers, a clean black tee, crisp white sneakers and a minimal watch.',
 'Tech interviews punish overdressing almost as much as underdressing — this greyscale capsule lands exactly in the middle. Monochrome basics in good fits read as intentional rather than lazy, and every piece recombines with the rest of a wardrobe.'),

('c1000000-0000-4000-a000-000000000016',
 'Corporate Shirt Rotation',
 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop&q=80',
 ARRAY['Internship (Corporate)', 'Office (Startup)', 'WFH / Video Call'],
 'Minimal',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Smart Casual', 'Conservative', 'All-season',
 ARRAY['Wine', 'White', 'Grey'],
 'A three-shirt working week: crisp white, dove grey and deep wine button-downs — rotate over tailored trousers or dark denim.',
 'A small rotation of impeccable shirts beats a large rotation of average ones — the first lesson of corporate dressing. Wine is the sleeper pick here: it reads as confident colour on camera and against every skin tone, where pale blue disappears.'),

-- ==================== SMART CASUAL & DAY DRESSING ===========================

('c1000000-0000-4000-a000-000000000017',
 'Wine Corduroy Midi Shirt-Dress',
 'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=600&auto=format&fit=crop&q=80',
 ARRAY['Brunch / Cafe', 'First Date', 'Office (Startup)', 'Dinner Date', 'College Farewell'],
 'Western',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Smart Casual', 'Conservative', 'Winter',
 ARRAY['Wine', 'Burgundy', 'Maroon'],
 'Deep wine corduroy midi shirt-dress with a button placket, three-quarter sleeves and a softly gathered waist.',
 'A shirt-dress is the hardest-working smart-casual piece a wardrobe can own — one zip-free garment, instantly put together. The gathered drop-waist is generous through the middle (kind to apple shapes), and wine corduroy brings texture and depth that flat cotton can''t.'),

('c1000000-0000-4000-a000-000000000018',
 'Powder Blue Trench Layers',
 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&auto=format&fit=crop&q=80',
 ARRAY['Airport / Travel Look', 'Hill Station Trip', 'Brunch / Cafe'],
 'Western',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky'],
 'Smart Casual', 'Conservative', 'Winter',
 ARRAY['Powder Blue', 'Sky Blue', 'Blush'],
 'Tonal powder-blue layering: a long trench over a matching midi, a soft scarf, white boots and a blush mini saddle bag.',
 'Dressing one colour in three tones is the fastest route to looking expensive — the eye reads it as a single elegant column. The trench''s straight line covers everything and flatters everyone, and the pastel family sits prettiest on fair-to-dusky skin.'),

('c1000000-0000-4000-a000-000000000019',
 'Burgundy Wrap Coat City Look',
 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&auto=format&fit=crop&q=80',
 ARRAY['Mall / Shopping Day', 'Casual Outing', 'Heritage City Sightseeing'],
 'Western',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Smart Casual', 'Conservative', 'Winter',
 ARRAY['Burgundy', 'Blush', 'Grey'],
 'Burgundy wrap coat over a blush rollneck with cat-eye sunglasses — a polished city-walking uniform.',
 'A wrap coat cinched at the waist gives structure to winter dressing without bulk, and burgundy flatters every Indian skin tone where camel can wash paler complexions out. Comfortable enough for a full day on your feet, sharp enough for every photo op along the way.'),

('c1000000-0000-4000-a000-000000000020',
 'Blush Joggers & Crop Chic',
 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600&auto=format&fit=crop&q=80',
 ARRAY['Brunch / Cafe', 'First Date', 'Mall / Shopping Day'],
 'Western',
 ARRAY['Hourglass', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky'],
 'Smart Casual', 'Moderate', 'Summer',
 ARRAY['Peach', 'Dusty Rose', 'White'],
 'Blush-pink relaxed joggers with flap pockets, a fitted white crop top and barely-there heels.',
 'Joggers with heels is the definitive off-duty-model trick — soft trousers, sharp shoes, instant tension. The added hip volume of a jogger balances an inverted triangle, and warm blush tones glow on fair to dusky skin at daytime.'),

('c1000000-0000-4000-a000-000000000021',
 'Light-Wash Denim Shirt Dress',
 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=600&auto=format&fit=crop&q=80',
 ARRAY['First Day of College', 'Casual Outing', 'Heritage City Sightseeing'],
 'Western',
 ARRAY['Hourglass', 'Pear', 'Rectangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Casual', 'Moderate', 'Summer',
 ARRAY['Denim Blue', 'Light Blue'],
 'Light-wash denim shirt dress with pearl-snap buttons, chest pockets and a gathered skirt that hits above the knee.',
 'Denim reads friendly and zero-effort — exactly the first-day-of-college message. The button-through fit-and-flare shape defines the waist without clinging anywhere, and it takes sneakers or sandals equally well.'),

-- ===================== CASUAL, STREET & COLLEGE =============================

('c1000000-0000-4000-a000-000000000022',
 'Graphic Crop & Light Denim',
 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&auto=format&fit=crop&q=80',
 ARRAY['College Fest (Day)', 'Casual Outing', 'Mall / Shopping Day'],
 'Streetwear',
 ARRAY['Hourglass', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Casual', 'Moderate', 'Summer',
 ARRAY['Black', 'Light Blue'],
 'Boxy black graphic crop tee with light-wash high-waist jeans and amber-tint sunglasses.',
 'The boxy-crop-plus-high-waist pairing shows an inch of midriff and nothing more — street cred with campus-appropriate ease. Black-on-light-denim is the most forgiving graphic-tee formula because the print, not the fit, carries the look.'),

('c1000000-0000-4000-a000-000000000023',
 'Scarlet Tee & Oversized Black Layer',
 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=600&auto=format&fit=crop&q=80',
 ARRAY['College Fest (Day)', 'Casual Outing', 'Mall / Shopping Day'],
 'Streetwear',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Casual', 'Moderate', 'All-season',
 ARRAY['Red', 'Black'],
 'Bright scarlet graphic tee under an oversized black overshirt, finished with retro two-tone sunglasses.',
 'Red under black is streetwear''s highest-contrast one-two — the jacket frames the colour instead of hiding it. Oversized layers democratise the look across every body type; the fit is a stance, not a measurement.'),

('c1000000-0000-4000-a000-000000000024',
 'Grey Hoodie Denim Layer-Up',
 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
 ARRAY['Hill Station Trip', 'College Trip', 'Travel Day'],
 'Streetwear',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Casual', 'Conservative', 'Winter',
 ARRAY['Grey', 'Denim Blue'],
 'Heather grey hoodie layered under a classic blue denim jacket — hood out, drawstrings loose.',
 'Hoodie-under-denim is the correct answer to hill-station weather: two light layers trap more heat than one heavy one, and you can shed as the sun climbs. It packs flat, shrugs off drizzle, and looks like you didn''t try — because on a trip, you shouldn''t.'),

('c1000000-0000-4000-a000-000000000025',
 'Rust Bomber Weekend Layer',
 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop&q=80',
 ARRAY['Casual Outing', 'College Fest (Day)', 'Airport / Travel Look'],
 'Streetwear',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Casual', 'Moderate', 'Winter',
 ARRAY['Rust', 'Terracotta'],
 'Lightweight rust-orange bomber with ribbed hems and a zip sleeve pocket — throw it over a white tee and black jeans.',
 'Rust is the rare streetwear colour that flatters warm Indian undertones better than black does — it picks up the gold in wheatish and dusky skin. A bomber''s ribbed waist stops it swallowing smaller frames the way a parka would.'),

('c1000000-0000-4000-a000-000000000026',
 'Double Denim Everyday',
 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&auto=format&fit=crop&q=80',
 ARRAY['Casual Outing', 'College Fest (Day)', 'Mall / Shopping Day'],
 'Western',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Casual', 'Moderate', 'All-season',
 ARRAY['Denim Blue', 'White'],
 'Mid-wash denim jacket with white contrast stitching over a plain white tee — the no-thought uniform that always lands.',
 'Denim on white is the most repeatable casual formula in existence; the jacket adds structure and the white keeps it fresh. One rule keeps double denim honest: keep the washes clearly different or exactly the same, never almost-matching.'),

('c1000000-0000-4000-a000-000000000027',
 'Everyday Black Tee & Light Denim',
 'https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=600&auto=format&fit=crop&q=80',
 ARRAY['Casual Outing', 'Mall / Shopping Day', 'WFH / Video Call'],
 'Minimal',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Casual', 'Moderate', 'All-season',
 ARRAY['Black', 'Light Blue'],
 'Relaxed black boyfriend tee half-tucked into light skinny jeans — the lowest-effort outfit that still looks decided.',
 'The half-tuck is doing all the work here: it marks the waist, breaks the column of black, and makes a plain tee read intentional. This is the outfit to own in triplicate — it survives video calls, errands and everything between.'),

-- ===================== HOLIDAY, TRAVEL & ACTIVE =============================

('c1000000-0000-4000-a000-000000000028',
 'White Cotton Holi Kit',
 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=600&auto=format&fit=crop&q=80',
 ARRAY['Holi', 'Gym / Workout', 'WFH / Video Call'],
 'Minimal',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 -- why Conservative: loose tee + full-length leggings covers arms-half/legs-full;
 -- this is exactly what modest dressers wear for Holi, and Modest users must
 -- not get zero results for a festival everyone attends.
 'Casual', 'Conservative', 'Summer',
 ARRAY['White', 'Black'],
 'Loose white printed cotton tee with black leggings — comfortable, washable, and ready to be ruined beautifully.',
 'Holi has exactly one dress code: white cotton you are happy to sacrifice, because gulal shows truest on white and cotton scrubs cleanest. Loose fit keeps you cool through hours of running around; the same kit doubles for the gym the other 364 days.'),

('c1000000-0000-4000-a000-000000000029',
 'White Floral Wrap Maxi by the Sea',
 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&auto=format&fit=crop&q=80',
 ARRAY['Beach / Pool Day', 'Travel Day', 'Brunch / Cafe'],
 'Western',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Casual', 'Moderate', 'Summer',
 ARRAY['White', 'Coral', 'Green'],
 'White wrap maxi scattered with coral-red roses, short flutter sleeves and a thigh-high front slit, carried with a woven straw bag.',
 'The wrap dress is the one silhouette stylists trust on literally every body — it ties to fit YOU rather than a size chart. Florals on white photograph like a holiday even when the trip is a Sunday brunch; the slit keeps it breezy, not bare.'),

('c1000000-0000-4000-a000-000000000030',
 'White Ruffle Off-Shoulder Mini',
 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&auto=format&fit=crop&q=80',
 ARRAY['Beach / Pool Day', 'Casual Outing', 'Mall / Shopping Day'],
 'Western',
 ARRAY['Hourglass', 'Pear', 'Rectangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Casual', 'Minimal', 'Summer',
 ARRAY['White'],
 'Breezy white off-shoulder mini with a ruffled neckline and tiered skirt, grounded with plain white sneakers.',
 'An off-shoulder neckline draws every eye to the collarbones and balances fuller hips — tailor-made for pear shapes. White-on-white with sneakers keeps a mini feeling daytime and sweet rather than evening; crisp white pops hardest against deeper skin.'),

('c1000000-0000-4000-a000-000000000031',
 'Teal Crochet Crop & Denim',
 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&auto=format&fit=crop&q=80',
 ARRAY['Beach / Pool Day', 'College Trip', 'Casual Outing'],
 'Western',
 ARRAY['Hourglass', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Casual', 'Minimal', 'Summer',
 ARRAY['Teal', 'Denim Blue'],
 'Teal crochet crop top with layered pendant chains and round sunnies — throw over denim cut-offs or a sarong at the beach.',
 'Crochet is beachwear that survives the cafe stop afterwards — texture makes a tiny top feel dressed. Teal against sun-warmed skin is spectacular on wheatish through deep tones, which is why this shade owns Goa.'),

('c1000000-0000-4000-a000-000000000032',
 'Weekender Capsule: Shirt, Breton & Denim',
 'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=600&auto=format&fit=crop&q=80',
 ARRAY['Travel Day', 'Airport / Travel Look', 'Heritage City Sightseeing'],
 'Minimal',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Casual', 'Moderate', 'All-season',
 ARRAY['White', 'Denim Blue', 'Red'],
 'The three-day packing answer: a crisp white shirt, red-striped breton tee, straight jeans and flat red sandals.',
 'Four pieces, six outfits — that is the whole philosophy of capsule packing. White shirt for sightseeing sun, breton for the cafe, and one red accent so every photo has a focal point. Everything here survives being rolled into a rucksack.'),

('c1000000-0000-4000-a000-000000000033',
 'Dot Chambray Video-Call Shirt',
 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
 ARRAY['WFH / Video Call', 'Casual Outing', 'First Day of College'],
 'Minimal',
 ARRAY['Hourglass', 'Pear', 'Apple', 'Rectangle', 'Inverted Triangle'],
 ARRAY['Fair', 'Wheatish', 'Dusky', 'Deep'],
 'Casual', 'Conservative', 'All-season',
 ARRAY['Denim Blue', 'White'],
 'Soft chambray shirt with a fine white dot print and three-quarter sleeves — collar sits perfectly on camera.',
 'On video calls the frame is chest-up, so the collar IS the outfit — chambray adds texture that flat cotton loses to webcam compression, and the small dot reads friendly without strobing on screen. Off camera it works open over a tank as a light layer.')

ON CONFLICT (id) DO NOTHING;
